config/routes.rb
Avatard::Application.routes.draw do

  resources :avatars

  match 'avatar/:id(.:format)' => 'avatars#show', :format => :png

  root :to => "avatars#index"

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base

  DEFAULT_SIZE = 50

  validates_presence_of :email
  validates_uniqueness_of :email

  image_accessor :avatar

  before_save :set_checksum

  def self.dimensions(size = Avatar::DEFAULT_SIZE)
    "#{size.to_s}x#{size.to_s}"
  end

  def set_checksum
    self.checksum = Digest::MD5.hexdigest(email)
  end

  def to_param
    checksum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def index
    @avatars = Avatar.all
    @avatar = Avatar.new
  end

  def show
    #puts y request
    begin
      @avatar = Avatar.find_by_checksum!(params[:id])

      if params[:s]
        s = params[:s].to_i.to_s
      else
        s = Avatar::DEFAULT_SIZE
      end
      size = "#{s}x#{s}"

      respond_to do |format|
        format.png  { redirect_to @avatar.avatar.thumb(size).url }
        format.html
      end
    rescue ActiveRecord::RecordNotFound
      # FIXME - Need to find the right way to do this, cannot access
      # the URL helpers from controller
      redirect_to "http://#{request.host_with_port}/images/default.png"
    end
  end

  def create
    @avatar = Avatar.new params[:avatar]
    if @avatar.save
      redirect_to avatars_url
    else
      @avatars = Avatar.all
      render :index
    end
  end

  def update
    @avatar = Avatar.find_by_checksum!(params[:id])

    if @avatar.email == params[:avatar][:email]
      if @avatar.update_attributes params[:avatar]
        redirect_to avatars_url
      else
        render 'show'
      end
    else
      @avatar.errors.add(:email, 'address no matchy')
      render 'show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/views/avatars/_form.html.erb
<% if @avatar.errors.any? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @avatar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :email %>
  <% if form.object.new_record? %>
    <%= form.text_field :email %>
  <% else %>
    <input type="text" name="avatar[email]" id="avatar_email">
  <% end %>
</p>
<p>
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
</p>
<%= form.submit %>

app/views/avatars/index.html.erb
<h2>New avatar</h2>

<%= form_for @avatar, :html => {:multipart => true} do |f| %>
<%= render f %>
<% end %>

<hr>

<% @avatars.each do |avatar| %>
  <%= link_to(image_tag(avatar.avatar.thumb('64x64').url), avatar_url(avatar)) %>
<% end %>

app/views/avatars/show.html.erb
<%= image_tag @avatar.avatar.thumb('200x200').url %>

<%= form_for @avatar, :html => {:multipart => true} do |form| %>
  <%= render form %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avatard</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <h1>Avatard</h1>

  <div class="content">
    <%= yield %>
  </div>

</body>
</html>